# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 
    ArtifactName: 'wmt_artifact'
    publishLocation: 'Container'
- task: CopyFiles@2
  inputs:
    SourceFolder: '/home/vsts/work/1/s/target/'
    Contents: 'petclinic.war'
    TargetFolder: '/home/vsts/work/1/a'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-X'
    goals: 'package'
    options: 'tomcat7:run'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
      docker run -e MYSQL_ROOT_PASSWORD=petclinic -e MYSQL_DATABASE=petclinic -p 3306:3306 mysql:5.7.8
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
